<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CourseInfo extends Model
{
    use HasFactory;
    protected $fillable = ['title', 'body', 'image', 'course_id'];

    public function course(){
        return $this->belongsTo(Course::class);
    }

//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//        CourseInfo::created(function ($course){
//            if(starts_with($course->image, 'public')){
//                $course->image = substr($course->image, 6);
//                $course->save();
//            }
//        });
//    }
}
