<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    use HasFactory;
    protected $fillable = ['title', 'image', 'body', 'duration', 'course_category_id'];
    public function course_category(){
        return $this->belongsTo(CourseCategory::class);
    }
    public function course_facts(){
        return $this->hasMany(CourseFacts::class);
    }
    public function course_infos(){
        return $this->hasMany(CourseInfo::class);
    }
    public function facts(){
        return $this->hasMany(Fact::class, 'course_id', 'id');
    }
    public function programs(){
        return $this->hasMany(Program::class);
    }
    public function certificate(){
        return $this->hasOne(Certificate::class);
    }
//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//        Course::created(function ($course){
//            if(starts_with($course->image, 'public')){
//                $course->image = substr($course->image, 6);
//                $course->save();
//            }
//        });
//    }
}
